-- Buka Supabase Dashboard -> SQL Editor -> New Query
-- Paste semua kode di bawah ini lalu klik RUN

-- 1. Hapus tabel lama jika ada (opsional)
drop table if exists public.profile_config cascade;

-- 2. Buat tabel konfigurasi profil
create table public.profile_config (
  id bigint primary key generated by default as identity,
  profile_name text not null default 'CENOT',
  profile_bio text not null default 'powerd by SANS DISCORD SERVER',
  avatar_url text not null default 'https://avatarfiles.alphacoders.com/174/174875.png',
  slogan text not null default 'aut vincere aut mori',
  links jsonb not null default '[]'::jsonb,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Masukkan data awal (default)
insert into public.profile_config (id, profile_name, profile_bio, avatar_url, slogan, links)
overriding system value
values (
  1,
  'CENOT',
  'powerd by SANS DISCORD SERVER',
  'https://avatarfiles.alphacoders.com/174/174875.png',
  'aut vincere aut mori',
  '{
    "bioLinks": [
      {"title": "webstore (soon)", "url": "https://toko.notnot.store", "iconType": "cart"},
      {"title": "MANGA", "url": "https://baca.notnot.store", "iconType": "book"},
      {"title": "PIALA DUNIA", "url": "https://bola.notnot.store", "iconType": "trophy"},
      {"title": "TikTok", "url": "https://www.tiktok.com/@ccenot", "iconType": "tiktok"},
      {"title": "Donasi", "url": "https://saweria.co/cenot", "iconType": "coffee"},
      {"title": "Discord", "url": "https://tr.ee/sans", "iconType": "discord"},
      {"title": "SPIN", "url": "/spin", "iconType": "sparkles"}
    ],
    "webLinks": [
      {"title": "Donasi", "url": "https://saweria.co/cenot", "iconType": "coffee"},
      {"title": "Discord", "url": "https://tr.ee/sans", "iconType": "discord"},
      {"title": "SPIN", "url": "/spin", "iconType": "sparkles"}
    ]
  }'::jsonb
) on conflict (id) do nothing;

-- 4. Aktifkan Row Level Security (RLS) agar aman
alter table public.profile_config enable row level security;

-- 5. Buat policy agar semua orang bisa baca data profil
create policy "Allow public read access" on public.profile_config 
  for select using (true);

-- 6. Buat policy agar admin bisa update/insert data memakai API key
create policy "Allow all write access" on public.profile_config 
  for all using (true) with check (true);
