import pkg from 'pg';
const { Client } = pkg;

const connectionString = process.env.SUPABASE_DB_URL || 'postgresql://postgres:your_password@db.your-project.supabase.co:5432/postgres';

const client = new Client({
  connectionString,
  ssl: {
    rejectUnauthorized: false
  }
});

const sql = `
-- 1. Buat tabel konfigurasi profil
create table if not exists public.profile_config (
  id bigint primary key generated by default as identity,
  profile_name text not null default 'CENOT',
  profile_bio text not null default 'powerd by SANS DISCORD SERVER',
  avatar_url text not null default 'https://avatarfiles.alphacoders.com/174/174875.png',
  slogan text not null default 'aut vincere aut mori',
  links jsonb not null default '[]'::jsonb,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Masukkan data awal profil jika belum ada
insert into public.profile_config (id, profile_name, profile_bio, avatar_url, slogan, links)
overriding system value
values (
  1,
  'CENOT',
  'powerd by SANS DISCORD SERVER',
  'https://avatarfiles.alphacoders.com/174/174875.png',
  'aut vincere aut mori',
  '[
    {"title": "webstore (soon)", "url": "https://toko.notnot.store", "iconType": "cart"},
    {"title": "MANGA", "url": "https://baca.notnot.store", "iconType": "book"},
    {"title": "PIALA DUNIA", "url": "https://bola.notnot.store", "iconType": "trophy"},
    {"title": "TikTok", "url": "https://www.tiktok.com/@ccenot", "iconType": "tiktok"},
    {"title": "Donasi", "url": "https://saweria.co/cenot", "iconType": "coffee"},
    {"title": "Discord", "url": "https://tr.ee/sans", "iconType": "discord"},
    {"title": "SPIN", "url": "/spin", "iconType": "sparkles"}
  ]'::jsonb
) on conflict (id) do nothing;

alter table public.profile_config enable row level security;
drop policy if exists "Allow public read access" on public.profile_config;
create policy "Allow public read access" on public.profile_config for select using (true);
drop policy if exists "Allow all write access" on public.profile_config;
create policy "Allow all write access" on public.profile_config for all using (true) with check (true);

-- 3. Buat tabel kredensial admin
create table if not exists public.admin_users (
  id bigint primary key generated by default as identity,
  username text unique not null default 'cenot',
  password_hash text not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

insert into public.admin_users (id, username, password_hash)
overriding system value
values (
  1,
  'cenot',
  'ef92b778bafe771e89245b89ecbc08a44a4e166c06659911881f383d4473e94f'
) on conflict (id) do nothing;

alter table public.admin_users enable row level security;
drop policy if exists "Allow auth read on admin_users" on public.admin_users;
create policy "Allow auth read on admin_users" on public.admin_users for select using (true);
drop policy if exists "Allow update on admin_users" on public.admin_users;
create policy "Allow update on admin_users" on public.admin_users for all using (true) with check (true);
`;

async function main() {
  try {
    console.log('Connecting to Supabase Database...');
    await client.connect();
    console.log('Connected! Executing SQL scripts...');
    await client.query(sql);
    console.log('Database initialized successfully with admin_users & profile_config!');
  } catch (err) {
    console.error('Error initializing database:', err);
  } finally {
    await client.end();
  }
}

main();
