import pkg from 'pg';
const { Client } = pkg;

const connectionString = process.env.SUPABASE_DB_URL || 'postgresql://postgres:your_password@db.your-project.supabase.co:5432/postgres';

const client = new Client({
  connectionString,
  ssl: {
    rejectUnauthorized: false
  }
});

const sql = `
-- Drop existing objects if they exist
drop table if exists public.profile_config cascade;

-- Buat tabel konfigurasi profil
create table public.profile_config (
  id bigint primary key generated by default as identity,
  profile_name text not null default 'CENOT',
  profile_bio text not null default 'powerd by SANS DISCORD SERVER',
  avatar_url text not null default 'https://avatarfiles.alphacoders.com/174/174875.png',
  slogan text not null default 'aut vincere aut mori',
  links jsonb not null default '[]'::jsonb,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Masukkan data awal (default)
insert into public.profile_config (id, profile_name, profile_bio, avatar_url, slogan, links)
overriding system value
values (
  1,
  'CENOT',
  'powerd by SANS DISCORD SERVER',
  'https://avatarfiles.alphacoders.com/174/174875.png',
  'aut vincere aut mori',
  '[
    {"title": "webstore (soon)", "url": "https://toko.notnot.store", "iconType": "cart"},
    {"title": "MANGA", "url": "https://baca.notnot.store", "iconType": "book"},
    {"title": "PIALA DUNIA", "url": "https://bola.notnot.store", "iconType": "trophy"},
    {"title": "TikTok", "url": "https://www.tiktok.com/@ccenot", "iconType": "tiktok"},
    {"title": "Donasi", "url": "https://saweria.co/cenot", "iconType": "coffee"},
    {"title": "Discord", "url": "https://tr.ee/sans", "iconType": "discord"}
  ]'::jsonb
) on conflict (id) do nothing;

-- Izinkan semua orang membaca data
alter table public.profile_config enable row level security;
create policy "Allow public read access" on public.profile_config for select using (true);
create policy "Allow all write access for public/service role" on public.profile_config for all using (true);
`;

async function main() {
  try {
    console.log('Connecting to Supabase Database...');
    await client.connect();
    console.log('Connected! Executing SQL scripts...');
    await client.query(sql);
    console.log('Database initialized successfully!');
  } catch (err) {
    console.error('Error initializing database:', err);
  } finally {
    await client.end();
  }
}

main();
